added some tests to increase the sonar code cov
digital-delivery-academy/simple-test-data-generator pull request #1
Opened 2021-01-12 13:28 UTC by kurt-uk

to increase the code cov, getter and setter tests were added

2021-01-13 14:51 UTC, stevewalton28 requested changes

2021-01-13 14:51 UTC, stevewalton28 commented on LICENSE
> +Copyright (c) 2020 Evoco Digital Services Ltd
2021

2021-01-13 14:51 UTC, stevewalton28 commented on README.md
> +- A full reference guide is here: https://digital-delivery-academy.github.io/selenium-pom-framework/index.html
Well we don't have these do we?  Remove all refs to the Selenium framework in the README I think

2021-01-13 14:51 UTC, stevewalton28 commented on src/test/java/uk/co/evoco/testdata/BankHolidaysTests.java
> +        bankHolidays.setLocale("scotland");
Could test for upper case, mixed case and no match to the ENUM here (e.g. UNITED_STATES)

2021-01-13 15:06 UTC, kurt-uk commented on LICENSE
> +Copyright (c) 2020 Evoco Digital Services Ltd
👍🏼

2021-01-13 15:08 UTC, kurt-uk commented on README.md
> +- A full reference guide is here: https://digital-delivery-academy.github.io/selenium-pom-framework/index.html
removed 👍🏼 
Id need a description of what we wanna put in the readme though, could be best for you to write, or send some bullet points for me and ill juice them up a bit

2021-01-13 15:42 UTC, kurt-uk commented on .all-contributorsrc
> +  "projectName": "selenium-pom-framework",
change

2021-01-14 09:39 UTC, stevewalton28 approved these changes

2021-01-14 09:40 UTC, merged